create database swiggy;

create table prediwali
(DT text,
ID	int,
City int,
namess varchar(100),
ITEM_ID	int,
ITEM_NAME varchar(100),
hr int,
orders int,
QTY int,
ITEM_GMV int,
CATEGORY char(100),
qt int
);

create table postdiwali
(
DT	text,
ID	int,
City int,
namess varchar(100),
ITEM_ID	int,
ITEM_NAME varchar(100),
hrofday int,
orders int,
QTY int,
ITEM_GMV int,
CATEGORY char(100)
);
/********NO OF SHOPS COUNT PREDIWALI****************/
select NAMESS,item_name,count(*) as no,
from PREDIWALI
group by NAMESS
ORDER BY 1
limit 20;
/**********NO OF SHOPS POST DIWALI***************************************/
select NAMESS,count(*) as no
from POSTDIWALI
group by NAMESS
ORDER BY 1
limit 20;
/**************************************************/
SELECT DT,NAMESS,ITEM_NAME,ORDERS
FROM PREDIWALI;
/*PRE AND POST DIWALI ORDER AND ITEM_GMV COMPARISION OF SAME ITEM*/
SELECT PRD.NAMESS ,PRD.ITEM_NAME ,PRD.HR,PRD.ORDERS  AS PREDIWALISALES, PRD.ITEM_GMV,
POD.NAMESS,POD.ITEM_NAME,POD.HROFDAY,POD.ORDERS AS POSTDIWALISALES,POD.ITEM_GMV
FROM POSTDIWALI AS POD,PREDIWALI AS PRD
WHERE POD.ITEM_ID=PRD.ITEM_ID
ORDER BY PRD.ORDERS,POD.ORDERS DESC;
/******NAME OF THE SHOP AND THE ITEM OF THAT SHOP WHO DINT SELL POST DIWALI*****/
SELECT PRD.NAMESS,PRD.ITEM_NAME,PRD.ORDERS
FROM PREDIWALI AS PRD,POSTDIWALI AS POD
WHERE PRD.ITEM_ID<>POD.ITEM_ID;
/****COMPARING THE SWEET SHOP SUM OF ORDERS PRE AND POST DIWALI****/
SELECT PRD.NAMESS,SUM(PRD.ORDERS),SUM(PRD.ITEM_GMV),
POD.NAMESS,SUM(POD.ORDERS),SUM(POD.ITEM_GMV)
FROM PREDIWALI AS PRD,POSTDIWALI AS POD
WHERE PRD.ITEM_ID=POD.ITEM_ID
GROUP BY POD.NAMESS,PRD.NAMESS
ORDER BY SUM(PRD.ITEM_GMV) DESC;
/*** NAME OF ITEM AND THE TOTAL ITEM GMV EARNED FROM THEM TO THE SHOP DURING PRE DIWALI***/
/***TOTAL ITEM_GMV OF ALL THE ITEMS IN DESC ORDER FOR PREDIWALI***/
SELECT NAMESS,ITEM_NAME,SUM(ITEM_GMV) AS TOTALGMV,MAX(ITEM_GMV)
FROM PREDIWALI
GROUP BY ITEM_NAME,NAMESS
ORDER BY SUM(ITEM_GMV) DESC;

/*** NAME OF ITEM AND THE TOTAL ITEM GMV EARNED FROM THEM TO THE SHOP DURING POST DIWALI***/
SELECT NAMESS,ITEM_NAME,SUM(ITEM_GMV) AS TOTALGMV,MAX(ITEM_GMV)
FROM POSTDIWALI
GROUP BY ITEM_NAME,NAMESS
ORDER BY SUM(ITEM_GMV) DESC;

SELECT NAMESS,CATEGORY,COUNT(CATEGORY) AS CNT
FROM PREDIWALI
GROUP BY CATEGORY;
/****************/
SELECT prd.dt,prd.item_name,prd.ORDERS,PRD.ITEM_GMV,PRD.HR,pod.dt,pod.item_name,pod.ORDERS,POD.ITEM_GMV,POD.HROFDAY
FROM PREDIWALI AS PRD,POSTDIWALI AS POD
WHERE PRD.NAMESS="CAKE PALACE" and POD.NAMESS ="CAKE PALACE" 
ORDER BY PRD.DT,POD.DT,PRD.ITEM_NAME,POD.ITEM_NAME;
/*****************/
SELECT PRD.NAMESS,PRD.ITEM_NAME,PRD.ORDERS,PRD.ITEM_GMV,
POD.NAMESS,POD.ITEM_NAME,POD.ORDERS,POD.ITEM_GMV
FROM prediwali AS PRD, POSTDIWALI AS POD
WHERE PRD.NAMESS=POD.NAMESS;


